Update demo.md
eWaterCycle/ewatercycle.github.io pull request #34
Opened 2022-07-06 12:57 UTC by RolfHut

updated demo.md to reflect that the explorer is open to all and only the jupyterhub requires a login

2022-07-07 06:25 UTC, RolfHut commented
added @Peter9192 as possible reviewer, one review for such a minor thing would be ok in my opinion.

2022-07-08 13:47 UTC, Peter9192 requested changes, later dismissed
Good idea to change, but I would phrase it differently

2022-07-08 13:47 UTC, Peter9192 commented on demo.md
> +Note that you can use the explorer to browse available models and datasets. To start an experiment on our Jupyterhub you need an account. Please contact us at questions@ewatercycle.org to get one.
```suggestion
Note that you need an account to start an experiment on our Jupyterhub. Please contact us at questions@ewatercycle.org to get one. Without an account, you can still browse the explorer. 
```

The "note" applies to "needing an account", so imho it's better to keep these subsentences together. Also, this makes it sound like the explorer shows all available models and datasets, but it shows only a subset.

2022-07-13 10:07 UTC, nielsdrost approved these changes

2022-07-13 10:07 UTC, merged